# Generated by Django 5.1.6 on 2025-07-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0005_cafe_latitude_cafe_longitude_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
